// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdJnCqs_9-leNsqicwItqnL2CF-_pnuQ',
    appId: '1:432784320511:web:311f54a74c82b4ab2c69ca',
    messagingSenderId: '432784320511',
    projectId: 'eduera-5573f',
    authDomain: 'eduera-5573f.firebaseapp.com',
    storageBucket: 'eduera-5573f.firebasestorage.app',
    measurementId: 'G-2G4729BYP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6WcvpiMYRr1rFvhqyqEVSvyYrxWkntQ',
    appId: '1:432784320511:android:87ec1a73d6aee2392c69ca',
    messagingSenderId: '432784320511',
    projectId: 'eduera-5573f',
    storageBucket: 'eduera-5573f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDugIEhkwWoRUhiGzHs6TnwXkrqrVUvyI8',
    appId: '1:432784320511:ios:97bd878bd0ff57a02c69ca',
    messagingSenderId: '432784320511',
    projectId: 'eduera-5573f',
    storageBucket: 'eduera-5573f.firebasestorage.app',
    iosClientId: '432784320511-sif71h6afif5cfbgpfv57epqvgh1tbgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.edueraStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDugIEhkwWoRUhiGzHs6TnwXkrqrVUvyI8',
    appId: '1:432784320511:ios:97bd878bd0ff57a02c69ca',
    messagingSenderId: '432784320511',
    projectId: 'eduera-5573f',
    storageBucket: 'eduera-5573f.firebasestorage.app',
    iosClientId: '432784320511-sif71h6afif5cfbgpfv57epqvgh1tbgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.edueraStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjdJnCqs_9-leNsqicwItqnL2CF-_pnuQ',
    appId: '1:432784320511:web:25812ab7b7cddd8a2c69ca',
    messagingSenderId: '432784320511',
    projectId: 'eduera-5573f',
    authDomain: 'eduera-5573f.firebaseapp.com',
    storageBucket: 'eduera-5573f.firebasestorage.app',
    measurementId: 'G-BSK34QCGCR',
  );

}